import './globals.css'
import { Rubik } from 'next/font/google'
import { AuthProvider } from './providers'
import SideBarNav from '@/components/SideBarNav'

const rubik = Rubik({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <AuthProvider>
          {/* <SideBarNav /> */}
          {children}
          </AuthProvider>
      </body>
    </html>
  )
}
